### ISSUE TITLE
Create a kafka cluster overview page

### ISSUE THREAD

**Issue by prapthik** [eyefloaters/console#154]
Create a kafka cluster overview page that shows:
Kafka cluster name
Status
Online nodes
Producers
Consumers
Controllers (in the future once Kraft is GA)
Cluster error and warnings
Number of Insync, underreplicated, offline partitions  
Graph of available disk space, Memory usage, CPU usage (One graph where user can change between these criterias)
Total bytes incoming and outgoing

![image](https://github.com/eyefloaters/console/assets/102235319/27b10cd8-d138-44ac-8d16-a83551809159)

Please refer to the Concept review Miro board to make sure you have the updated version of the mockup
https://miro.com/app/board/uXjVNbMAIcU=/?share_link_id=826973870733

**Comment by MikeEdgar** [comment]
Right - a few I can mention that are not yet implemented:
- count or listing of producers (MVP?)
- topic throughput metrics (MVP?)
- disk space metrics
- information for the errors/warnings section (MVP?)

I think the "Active controllers" count may be related to KRaft mode and I'm not entirely sure that information is available to us via the Kafka API (yet). @tombentley are you aware of anything being available in the future? The `describeCluster` operation only will give a single controller.

We'll also need to understand how the topic status information in the upper-right corner is determined.

**Comment by riccardo-forina** [comment]
That's Kubernetes's status for resources. See the topics on my cluster:

```
kubectl get KafkaTopic -n kafka
NAME                                                                                               CLUSTER    PARTITIONS   REPLICATION FACTOR   READY
asd                                                                                                zomgrofl   1            1                    True
asd3                                                                                               zomgrofl   1            1                    True
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a                                        zomgrofl   50           1                    True
my-topic                                                                                           zomgrofl   1            1                    True
strimzi-store-topic---effb8e3e057afce1ecf67c3f5d8e4e3ff177fc55                                     zomgrofl   1            1                    True
strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b   zomgrofl   1            1                    True
test                                                                                               zomgrofl   1            1                    True
test1                                                                                              zomgrofl   1            1                    True
test2                                                                                              zomgrofl   1            1                    True
test22                                                                                             zomgrofl   1            1                    True
topic-test                                                                                         zomgrofl   3            1                    True
topic1                                                                                             zomgrofl   1            1                    True
topic11                                                                                            zomgrofl   1            1                    True
topic22                                                                                            zomgrofl   1            1                    True
topic222                                                                                           zomgrofl   1            1                    True
topic3                                                                                             zomgrofl   1            1                    True
topic4                                                                                             zomgrofl   1            1                    True
topic5                                                                                             zomgrofl   1            1                    True
topic6                                                                                             zomgrofl   1            1                    True
topic7                                                                                             zomgrofl   1            1                    True
topic8                                                                                             zomgrofl   1            1                    True
topic9                                                                                             zomgrofl   1            1                    True
```

**Comment by MikeEdgar** [comment]
> That's Kubernetes's status for resources.

Correct. We'll need to determine a status from the topic itself that takes into account replication lag, offline partitions, etc.

**Comment by riccardo-forina** [comment]
There is a comment from @shirimordechay on Miro here https://miro.com/app/board/uXjVNbMAIcU=/?openComment=3458764567907996429 where she states that for MVP we can have "Ready" and "Under replicated", which should mean we just need to define what "Under replicated" means, if there is no official definition for that

**Comment by MikeEdgar** [comment]
> which should mean we just need to define what "Under replicated" means, if there is no official definition for that

I'm not sure if there is an official definition. However, we do have an `inSync` property for each entry of a Topic's `attributes.partitions[].replicas[]` that may be useful. Perhaps if any replica has `inSync=false` it should trigger the "Under replicated" status.

**Comment by riccardo-forina** [comment]
I'm already getting access to the `partitions` I think, to show the count. Seeking for that flag should be trivial.
