### ISSUE TITLE
Include a basic topic status 

### ISSUE THREAD

**Issue by shirimordechay** [eyefloaters/console#165]
Include topic statuses we want to surface for [MVP](https://miro.com/app/board/uXjVNbMAIcU=/?moveToWidget=3458764566856711261&cot=14):
1. In-sync- Topic is available and all partition replicas are in-sync (see under-replicated definition) 
2. Under-replicated: A partition is under-replicated if some replicas are not 'in sync'. A replica is 'in sync' if the follower has fetched records up to the log end offset within replica.lag.time.max.ms. 

The topic status will surface in the following places: 
1. Cluster overview: Show an aggregated number of in-sync/ Under-replicated topics with the ability to click and drill down to a pre-filtered topic list. 
2. Topic list: Status column, provide a tooltip when the status is under-replicated with the number of under-replicated replicas, filter list by "All statuses, In-sync, Under-replicated."

@katheris

**Comment by MikeEdgar** [comment]
This is mostly completed (via #219) with the exception of tool tips and the cluster overview, which is a draft PR currently, #206.
