### ISSUE TITLE
From the topic configuration tab, when clicking on Messages tab the console crashes 

### ISSUE THREAD

**Issue by shirimordechay** [eyefloaters/console#479]
**Describe the bug**
From the topic configuration tab, when clicking on the Messages tab the console crashes 

**To Reproduce**
1. Go to a topic page 
2. Click on the Configuration tab
3. Click on the messages tab 
4. See white screen 

**Expected behavior**
It shouldn't crash :) 

**Screenshots**
https://github.com/eyefloaters/console/assets/10331355/23419208-ca11-4145-a02c-459f527ce751

**Comment by riccardo-forina** [comment]
It looks like the fix didn't work
