### ISSUE TITLE
Records Page (Message Browser)

### ISSUE THREAD

**Issue by paoloantinori** [eyefloaters/console#54]
- [x] List
- [x] View (text)
  API: all record data available in response (text only)
- [x] Seek to offset/time
  API: seek functionality is available

**Comment by riccardo-forina** [comment]
List view
<img width="1373" alt="image" src="https://github.com/eyefloaters/console/assets/966316/96e526a7-7a32-41ff-b7cd-9f76f4b85796">

**Comment by riccardo-forina** [comment]
Done in #68
