### ISSUE TITLE
Non configured Kafka clusters enhancement 

### ISSUE THREAD

**Issue by shirimordechay** [eyefloaters/console#549]
**Describe the bug**
When a Kafka cluster is not configured, provide additional information to users. 

**To Reproduce**
https://github.com/eyefloaters/console/pull/544#event-12003186243 

**Expected behavior**
When a Kafka cluster is not configured, the cluster status should be "Connection not configured", with the ability to hover on the status and learn more about the issue + link to docs/ guide. 
![image](https://github.com/eyefloaters/console/assets/10331355/93fe400a-654b-4607-82ef-d2ce06511ada)
![image](https://github.com/eyefloaters/console/assets/10331355/0fecf25d-cff8-4b71-bf47-1d756dbb8d51)
(info text needs to be determined) 
*** The cluster status column should be added to the home page.

**Comment by riccardo-forina** [comment]
I think we can close this as it's been decided not to show unconfigured clusters.
